name: territoria
description: A GPS-based territory capture game PWA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Map and GPS
  flutter_map: ^6.0.0
  # flutter_map_tile_caching: ^9.0.0  # Temporarily disabled - requires newer SDK
  geolocator: ^10.1.0
  geolocator_web: ^2.2.0
  permission_handler: ^11.2.0
  
  # Geometry operations
  turf: ^0.0.8
  
  # Data persistence (temporarily disabled for deployment)
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  
  # Utilities
  latlong2: ^0.9.0
  provider: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true